AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 125

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers:
    - md5
    - sha1
    - sha256
    - sha512

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MixinUsage:
  Exclude:
    # For Scripts to Rule Them All
    - script/*

Metrics/MethodLength:
  Max: 20
