title: Ruby Versions
email: veganstraightedge+rubyversions@gmail.com
description: All versions of all Ruby implementations
url: "https://rubyversions.com"
github_username:  rubyversions

# Build settings
# theme: minima
plugins:
  - jekyll-feed
